server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          username: CucumberJar
          password: Vbhrf2006V
          uri: https://github.com/CucumberJar/config.git
          default-label: main